### PR TITLE
Hide the display splash screen on init

### PR DESCRIPTION
**Pull request by mcauser**

### CODE REVIEW

**Comment by tuupola** [comment]
Awesome. This was on my todo list for a while...

**Comment by mcauser** [comment]
Would you believe, shortly after committing this, I cracked the screen on my M5Stack!
Now I have to wait another 2-3 weeks for a replacement TFT :(

**Comment by tuupola** [comment]
Ouch :( Dropped on the floor?

**Comment by mcauser** [comment]
I noticed the alignment of the TFT was slightly off, obscuring the bottom row of pixels, so I took it apart to carefully reposition it, but accidentally made a tiny little tear in the ribbon cable, resulting in a unresponsive plain white screen.

If you need access to the screen, pry the front bezel off and access it from in front of the pcb.
The pcb needs to be moved sideways to detach from the shell, and this movement puts stress on the TFT ribbon cable. In my case, tearing it.

**Pull request merged**
